version: '3.8'

services:

  mariadb:
    build:
      context: /home/chaguer/Desktop/Inception/srcs/requirements/mariadb/.
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: hchaguer
      MYSQL_PASSWORD: mypass
  # nginx:
  #   build:
  #     context: /home/chaguer/Desktop/Inception/srcs/requirements/ngnix/.
  #   ports:
  #     - "8080:443"
    