version: '3.8'

services:

  mariadb:
    build:
      context: requirements/mariadb/.
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: MYDB
      MYSQL_USER: hchaguer
      MYSQL_PASSWORD: pass

  wordpress:
    build:
      context: requirements/wordpress
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    # networks:
    #   - inc
    # volumes:
    #   -data:/var/www/html
    environment:
      MYSQL_DATABASE: MYDB
      MYSQL_USER: hchaguer
      MYSQL_PASSWORD: pass

  nginx:
    build: 
      context: requirements/ngnix/.
    ports:
      - 443:443
    
    