version: '3.8'

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: requirements/mariadb
    ports:
      - "3306"
    networks:
      - inc
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: requirements/wordpress
    ports:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - inc
    volumes:
      - wordpress:/var/www/html
    env_file: .env

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: requirements/nginx/.
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inc
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    restart: always

networks:
  inc:
    name: net
    driver: bridge

volumes:
  wordpress:
    name : wordpress
    driver: local
    driver_opts :
      o: bind
      device: /home/chaguer/data/wordpress/
      type: none

  mariadb:
    name : mariadb
    driver: local
    driver_opts :
      o: bind
      device: /home/chaguer/data/mariadb/
      type: none
    
    